export async function load() {
  // Get projects data from API or database
  const projects = [
    {
      id: 1,
      name: 'Atacama Solar Park',
      location: 'Antofagasta, Chile',
      type: 'Solar',
      capacity: '250 MW',
      investment: 250000000,
      minimumInvestment: 5000000,
      investmentType: 'equity',
      riskScore: 2.8,
      riskLevel: 'Medium',
      irr: 12.5,
      status: 'Operational',
      image: 'https://images.pexels.com/photos/15751137/pexels-photo-15751137/free-photo-of-top-view-of-a-solar-panels.jpeg?auto=compress&cs=tinysrgb&w=600',
      developer: 'Solaris Energy',
      description: 'Large-scale solar PV project in the Atacama Desert.',
      riskDetails: {
        sentiment: 'Positive',
        marketAnalysis: 'Stable',
        regulatory: 'Favorable',
        technical: 'Proven',
        environmental: 'Low Impact'
      }
    },
    {
      id: 2,
      name: 'Patagonia Wind Farm',
      location: 'Santa Cruz, Argentina',
      type: 'Wind',
      capacity: '150 MW',
      investment: 180000000,
      minimumInvestment: 2500000,
      investmentType: 'mixed',
      riskScore: 3.2,
      riskLevel: 'Medium',
      irr: 11.8,
      status: 'Under Construction',
      image: 'https://images.pexels.com/photos/1108814/pexels-photo-1108814.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=1',
      developer: 'WindTech Solutions',
      description: 'Wind farm in Patagonia region with strong wind resources.',
      riskDetails: {
        sentiment: 'Positive',
        marketAnalysis: 'Growing',
        regulatory: 'Stable',
        technical: 'Proven',
        environmental: 'Moderate Impact'
      }
    },
    {
      id: 3,
      name: 'Amazon Hydro Project',
      location: 'Pará, Brazil',
      type: 'Hydro',
      capacity: '500 MW',
      investment: 750000000,
      minimumInvestment: 10000000,
      investmentType: 'debt',
      riskScore: 3.8,
      riskLevel: 'High',
      irr: 14.2,
      status: 'Development',
      image: 'https://images.pexels.com/photos/279283/pexels-photo-279283.jpeg?auto=compress&cs=tinysrgb&w=800',
      developer: 'HydroWorks',
      description: 'Hydroelectric project in the Amazon region.',
      riskDetails: {
        sentiment: 'Mixed',
        marketAnalysis: 'Volatile',
        regulatory: 'Complex',
        technical: 'Challenging',
        environmental: 'High Impact'
      }
    },
    {
      id: 4,
      name: 'Baja Solar Farm',
      location: 'Baja California, Mexico',
      type: 'Solar',
      capacity: '300 MW',
      investment: 300000000,
      minimumInvestment: 3000000,
      investmentType: 'equity',
      riskScore: 2.3,
      riskLevel: 'Low',
      irr: 10.8,
      status: 'Operational',
      image: 'https://images.pexels.com/photos/4878644/pexels-photo-4878644.jpeg?auto=compress&cs=tinysrgb&w=800',
      developer: 'SunPower Inc',
      description: 'Large solar farm in the sunny Baja region.',
      riskDetails: {
        sentiment: 'Very Positive',
        marketAnalysis: 'Stable',
        regulatory: 'Favorable',
        technical: 'Proven',
        environmental: 'Low Impact'
      }
    },
    {
      id: 5,
      name: 'Andes Geothermal',
      location: 'Antofagasta, Chile',
      type: 'Geothermal',
      capacity: '100 MW',
      investment: 200000000,
      minimumInvestment: 4000000,
      investmentType: 'tax equity',
      riskScore: 3.5,
      riskLevel: 'High',
      irr: 13.5,
      status: 'Under Construction',
      image: 'https://images.pexels.com/photos/534371/pexels-photo-534371.jpeg?auto=compress&cs=tinysrgb&w=600',
      developer: 'GeoTech Energy',
      description: 'Geothermal power plant utilizing the volcanic activity in the Andes mountains.',
      riskDetails: {
        sentiment: 'Positive',
        marketAnalysis: 'Emerging',
        regulatory: 'Complex',
        technical: 'Innovative',
        environmental: 'Moderate Impact'
      }
    },
    {
      id: 6,
      name: 'Caribbean Biomass Plant',
      location: 'Santo Domingo, Dominican Republic',
      type: 'Biomass',
      capacity: '50 MW',
      investment: 100000000,
      minimumInvestment: 1000000,
      investmentType: 'mixed',
      riskScore: 3.0,
      riskLevel: 'Medium',
      irr: 12.0,
      status: 'Development',
      image: 'https://images.pexels.com/photos/31552837/pexels-photo-31552837/free-photo-of-natural-woodpile-of-cut-logs-in-a-forest-setting.jpeg?auto=compress&cs=tinysrgb&w=600',
      developer: 'BioPower Caribbean',
      description: 'Biomass power plant utilizing agricultural waste from the region.',
      riskDetails: {
        sentiment: 'Neutral',
        marketAnalysis: 'Growing',
        regulatory: 'Supportive',
        technical: 'Proven',
        environmental: 'Positive Impact'
      }
    },
    
    // Additional 12 projects to create a total of 18 (3 pages x 6 projects)
    {
      id: 7,
      name: 'Nordic Offshore Wind',
      location: 'Copenhagen, Denmark',
      type: 'Wind',
      capacity: '400 MW',
      investment: 650000000,
      minimumInvestment: 8000000,
      investmentType: 'debt',
      riskScore: 2.5,
      riskLevel: 'Medium',
      irr: 9.8,
      status: 'Operational',
      image: 'https://images.pexels.com/photos/8011458/pexels-photo-8011458.jpeg?auto=compress&cs=tinysrgb&w=600',
      developer: 'Nordic Wind Power',
      description: 'Offshore wind farm in the North Sea with advanced turbine technology.',
      riskDetails: {
        sentiment: 'Positive',
        marketAnalysis: 'Stable',
        regulatory: 'Favorable',
        technical: 'Proven',
        environmental: 'Low Impact'
      }
    },
    {
      id: 8,
      name: 'Sahara Solar Thermal',
      location: 'Ouarzazate, Morocco',
      type: 'Solar',
      capacity: '180 MW',
      investment: 420000000,
      minimumInvestment: 4500000,
      investmentType: 'equity',
      riskScore: 3.0,
      riskLevel: 'Medium',
      irr: 11.5,
      status: 'Operational',
      image: 'https://images.pexels.com/photos/7527908/pexels-photo-7527908.jpeg?auto=compress&cs=tinysrgb&w=600',
      developer: 'ACWA Power',
      description: 'Concentrated solar power plant using mirror arrays and thermal storage.',
      riskDetails: {
        sentiment: 'Positive',
        marketAnalysis: 'Growing',
        regulatory: 'Favorable',
        technical: 'Proven',
        environmental: 'Low Impact'
      }
    },
    {
      id: 9,
      name: 'Blue Ocean Tidal',
      location: 'Bay of Fundy, Canada',
      type: 'Tidal',
      capacity: '20 MW',
      investment: 120000000,
      minimumInvestment: 1500000,
      investmentType: 'passive investment',
      riskScore: 4.2,
      riskLevel: 'High',
      irr: 15.8,
      status: 'Development',
      image: 'https://images.pexels.com/photos/4666753/pexels-photo-4666753.jpeg?auto=compress&cs=tinysrgb&w=800',
      developer: 'Tidal Energy Ltd',
      description: 'Tidal stream energy project harnessing the powerful bay currents.',
      riskDetails: {
        sentiment: 'Mixed',
        marketAnalysis: 'Emerging',
        regulatory: 'Complex',
        technical: 'Innovative',
        environmental: 'Moderate Impact'
      }
    },
    {
      id: 10,
      name: 'Queensland Battery Storage',
      location: 'Brisbane, Australia',
      type: 'Storage',
      capacity: '150 MWh',
      investment: 120000000,
      minimumInvestment: 2000000,
      investmentType: 'tax equity',
      riskScore: 2.7,
      riskLevel: 'Medium',
      irr: 10.5,
      status: 'Under Construction',
      image: 'https://images.pexels.com/photos/2582936/pexels-photo-2582936.jpeg?auto=compress&cs=tinysrgb&w=600',
      developer: 'Auspower Storage',
      description: 'Grid-scale battery storage facility enhancing renewable integration.',
      riskDetails: {
        sentiment: 'Positive',
        marketAnalysis: 'Growing',
        regulatory: 'Favorable',
        technical: 'Proven',
        environmental: 'Low Impact'
      }
    },
    {
      id: 11,
      name: 'Kenyan Geothermal Plant',
      location: 'Olkaria, Kenya',
      type: 'Geothermal',
      capacity: '140 MW',
      investment: 290000000,
      minimumInvestment: 3000000,
      investmentType: 'debt',
      riskScore: 3.3,
      riskLevel: 'Medium',
      irr: 13.2,
      status: 'Operational',
      image: 'https://images.pexels.com/photos/464401/pexels-photo-464401.jpeg?auto=compress&cs=tinysrgb&w=600',
      developer: 'KenGen',
      description: 'Geothermal power plant in the Great Rift Valley.',
      riskDetails: {
        sentiment: 'Positive',
        marketAnalysis: 'Stable',
        regulatory: 'Supportive',
        technical: 'Proven',
        environmental: 'Low Impact'
      }
    },
    {
      id: 12,
      name: 'Mekong River Dam',
      location: 'Luang Prabang, Laos',
      type: 'Hydro',
      capacity: '1,400 MW',
      investment: 2300000000,
      minimumInvestment: 20000000,
      investmentType: 'mixed',
      riskScore: 4.0,
      riskLevel: 'High',
      irr: 16.2,
      status: 'Development',
      image: 'https://images.pexels.com/photos/15120315/pexels-photo-15120315.jpeg?auto=compress&cs=tinysrgb&w=800',
      developer: 'Mekong Power Corp',
      description: 'Large-scale hydroelectric dam with extensive reservoir.',
      riskDetails: {
        sentiment: 'Mixed',
        marketAnalysis: 'Stable',
        regulatory: 'Complex',
        technical: 'Proven',
        environmental: 'High Impact'
      }
    },
    {
      id: 13,
      name: 'Scandinavian Floating Wind',
      location: 'Stavanger, Norway',
      type: 'Wind',
      capacity: '88 MW',
      investment: 280000000,
      minimumInvestment: 3500000,
      investmentType: 'equity',
      riskScore: 3.6,
      riskLevel: 'High',
      irr: 12.9,
      status: 'Under Construction',
      image: 'https://images.pexels.com/photos/532192/pexels-photo-532192.jpeg?auto=compress&cs=tinysrgb&w=600',
      developer: 'Equinor Renewables',
      description: 'Floating offshore wind farm using innovative platform technology.',
      riskDetails: {
        sentiment: 'Positive',
        marketAnalysis: 'Growing',
        regulatory: 'Favorable',
        technical: 'Innovative',
        environmental: 'Low Impact'
      }
    },
    {
      id: 14,
      name: 'Mojave Desert Solar',
      location: 'California, USA',
      type: 'Solar',
      capacity: '550 MW',
      investment: 900000000,
      minimumInvestment: 10000000,
      investmentType: 'tax equity',
      riskScore: 2.1,
      riskLevel: 'Low',
      irr: 8.9,
      status: 'Operational',
      image: 'https://images.pexels.com/photos/6996421/pexels-photo-6996421.jpeg?auto=compress&cs=tinysrgb&w=600',
      developer: 'NextEra Energy',
      description: 'Utility-scale solar farm with single-axis tracking technology.',
      riskDetails: {
        sentiment: 'Very Positive',
        marketAnalysis: 'Stable',
        regulatory: 'Very Favorable',
        technical: 'Proven',
        environmental: 'Low Impact'
      }
    },
    {
      id: 15,
      name: 'Baltic Biomass Cogeneration',
      location: 'Vilnius, Lithuania',
      type: 'Biomass',
      capacity: '70 MW',
      investment: 140000000,
      minimumInvestment: 1750000,
      investmentType: 'debt',
      riskScore: 2.8,
      riskLevel: 'Medium',
      irr: 11.2,
      status: 'Operational',
      image: 'https://images.pexels.com/photos/15525689/pexels-photo-15525689/free-photo-of-logs-in-moss.jpeg?auto=compress&cs=tinysrgb&w=600',
      developer: 'Baltic Green Energy',
      description: 'Biomass cogeneration plant providing electricity and district heating.',
      riskDetails: {
        sentiment: 'Positive',
        marketAnalysis: 'Stable',
        regulatory: 'Favorable',
        technical: 'Proven',
        environmental: 'Positive Impact'
      }
    },
    {
      id: 16,
      name: 'Wave Energy Scotland',
      location: 'Orkney Islands, Scotland',
      type: 'Wave',
      capacity: '10 MW',
      investment: 85000000,
      minimumInvestment: 1000000,
      investmentType: 'passive investment',
      riskScore: 4.5,
      riskLevel: 'High',
      irr: 16.5,
      status: 'Development',
      image: 'https://images.pexels.com/photos/2374666/pexels-photo-2374666.jpeg?auto=compress&cs=tinysrgb&w=600',
      developer: 'Wave Power Innovations',
      description: 'Wave energy converters harnessing powerful North Atlantic swells.',
      riskDetails: {
        sentiment: 'Mixed',
        marketAnalysis: 'Emerging',
        regulatory: 'Supportive',
        technical: 'Experimental',
        environmental: 'Low Impact'
      }
    },
    {
      id: 17,
      name: 'Vietnamese Floating Solar',
      location: 'Da Nang, Vietnam',
      type: 'Solar',
      capacity: '120 MW',
      investment: 150000000,
      minimumInvestment: 2500000,
      investmentType: 'mixed',
      riskScore: 3.0,
      riskLevel: 'Medium',
      irr: 11.7,
      status: 'Under Construction',
      image: 'https://images.pexels.com/photos/371917/pexels-photo-371917.jpeg?auto=compress&cs=tinysrgb&w=600',
      developer: 'Vietnam Renewable Energy',
      description: 'Floating solar farm on reservoir, maximizing land use efficiency.',
      riskDetails: {
        sentiment: 'Positive',
        marketAnalysis: 'Growing',
        regulatory: 'Improving',
        technical: 'Proven',
        environmental: 'Low Impact'
      }
    },
    {
      id: 18,
      name: 'Iceland Hydrogen Production',
      location: 'Reykjavik, Iceland',
      type: 'Hydrogen',
      capacity: '30 MW',
      investment: 120000000,
      minimumInvestment: 3000000,
      investmentType: 'equity',
      riskScore: 3.7,
      riskLevel: 'High',
      irr: 14.5,
      status: 'Development',
      image: '/images/hydroelectric-power-pipes.jpg',
      developer: 'Green Hydrogen Systems',
      description: 'Green hydrogen production facility powered by geothermal and hydroelectric energy.',
      riskDetails: {
        sentiment: 'Positive',
        marketAnalysis: 'Emerging',
        regulatory: 'Favorable',
        technical: 'Innovative',
        environmental: 'Positive Impact'
      }
    }
  ];

  // Return data for use in the page
  return {
    projects
  };
} 